// Generated by scripts/export-demo.ts from a stored analysis. Don't edit by
// hand: run the pipeline again and re-export.

import type { StoredMap } from "../analyses/map.ts";

export const demo: StoredMap = {
 "repoOwner": "shadcn-ui",
 "repoName": "taxonomy",
 "commitSha": "298a8857c7128a0d121e7f699dfd729f23b3966d",
 "adapter": "nextjs",
 "status": "complete",
 "finishedAt": "2026-10-08T23:06:19.827504+00:00",
 "coverage": {
  "files": {
   "found": 186,
   "parsed": 129,
   "skipped": 57
  },
  "imports": {
   "seen": 513,
   "internal": 258,
   "external": 231,
   "excluded": 17,
   "unresolved": 7
  },
  "unresolvedByReason": {
   "alias-target-not-found": 7
  },
  "excludedByReason": {
   "non-code-file": 6,
   "declaration-file": 11
  }
 },
 "files": [
  {
   "path": "app/(auth)/layout.tsx",
   "folder": "app/(auth)",
   "lines": 7,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "app/(auth)/login/page.tsx",
   "folder": "app/(auth)/login",
   "lines": 51,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(auth)/register/page.tsx",
   "folder": "app/(auth)/register",
   "lines": 59,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(dashboard)/dashboard/billing/loading.tsx",
   "folder": "app/(dashboard)/dashboard/billing",
   "lines": 17,
   "role": "boundary",
   "label": null,
   "fanIn": 0,
   "fanOut": 3
  },
  {
   "path": "app/(dashboard)/dashboard/billing/page.tsx",
   "folder": "app/(dashboard)/dashboard/billing",
   "lines": 76,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 10
  },
  {
   "path": "app/(dashboard)/dashboard/layout.tsx",
   "folder": "app/(dashboard)/dashboard",
   "lines": 48,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 6
  },
  {
   "path": "app/(dashboard)/dashboard/loading.tsx",
   "folder": "app/(dashboard)/dashboard",
   "lines": 21,
   "role": "boundary",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(dashboard)/dashboard/page.tsx",
   "folder": "app/(dashboard)/dashboard",
   "lines": 63,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 8
  },
  {
   "path": "app/(dashboard)/dashboard/settings/loading.tsx",
   "folder": "app/(dashboard)/dashboard/settings",
   "lines": 18,
   "role": "boundary",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(dashboard)/dashboard/settings/page.tsx",
   "folder": "app/(dashboard)/dashboard/settings",
   "lines": 32,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 5
  },
  {
   "path": "app/(docs)/docs/[[...slug]]/page.tsx",
   "folder": "app/(docs)/docs/[[...slug]]",
   "lines": 107,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 7
  },
  {
   "path": "app/(docs)/docs/layout.tsx",
   "folder": "app/(docs)/docs",
   "lines": 17,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 2
  },
  {
   "path": "app/(docs)/guides/[...slug]/page.tsx",
   "folder": "app/(docs)/guides/[...slug]",
   "lines": 117,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 8
  },
  {
   "path": "app/(docs)/guides/layout.tsx",
   "folder": "app/(docs)/guides",
   "lines": 7,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "app/(docs)/guides/page.tsx",
   "folder": "app/(docs)/guides",
   "lines": 65,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 2
  },
  {
   "path": "app/(docs)/layout.tsx",
   "folder": "app/(docs)",
   "lines": 44,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 7
  },
  {
   "path": "app/(editor)/editor/[postId]/loading.tsx",
   "folder": "app/(editor)/editor/[postId]",
   "lines": 18,
   "role": "boundary",
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "app/(editor)/editor/[postId]/not-found.tsx",
   "folder": "app/(editor)/editor/[postId]",
   "lines": 19,
   "role": "boundary",
   "label": null,
   "fanIn": 0,
   "fanOut": 2
  },
  {
   "path": "app/(editor)/editor/[postId]/page.tsx",
   "folder": "app/(editor)/editor/[postId]",
   "lines": 45,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(editor)/editor/layout.tsx",
   "folder": "app/(editor)/editor",
   "lines": 11,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "app/(marketing)/[...slug]/page.tsx",
   "folder": "app/(marketing)/[...slug]",
   "lines": 99,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(marketing)/blog/[...slug]/page.tsx",
   "folder": "app/(marketing)/blog/[...slug]",
   "lines": 169,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 5
  },
  {
   "path": "app/(marketing)/blog/page.tsx",
   "folder": "app/(marketing)/blog",
   "lines": 69,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "app/(marketing)/layout.tsx",
   "folder": "app/(marketing)",
   "lines": 38,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 5
  },
  {
   "path": "app/(marketing)/page.tsx",
   "folder": "app/(marketing)",
   "lines": 226,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/(marketing)/pricing/page.tsx",
   "folder": "app/(marketing)/pricing",
   "lines": 69,
   "role": "page",
   "label": null,
   "fanIn": 0,
   "fanOut": 3
  },
  {
   "path": "app/api/auth/[...nextauth]/_route.ts",
   "folder": "app/api/auth/[...nextauth]",
   "lines": 7,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "app/api/og/route.tsx",
   "folder": "app/api/og",
   "lines": 148,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "app/api/posts/[postId]/route.ts",
   "folder": "app/api/posts/[postId]",
   "lines": 93,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 3
  },
  {
   "path": "app/api/posts/route.ts",
   "folder": "app/api/posts",
   "lines": 92,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 4
  },
  {
   "path": "app/api/users/[userId]/route.ts",
   "folder": "app/api/users/[userId]",
   "lines": 50,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 3
  },
  {
   "path": "app/api/users/stripe/route.ts",
   "folder": "app/api/users/stripe",
   "lines": 61,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 5
  },
  {
   "path": "app/api/webhooks/stripe/route.ts",
   "folder": "app/api/webhooks/stripe",
   "lines": 71,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 3
  },
  {
   "path": "app/layout.tsx",
   "folder": "app",
   "lines": 94,
   "role": "layout",
   "label": null,
   "fanIn": 0,
   "fanOut": 6
  },
  {
   "path": "app/robots.ts",
   "folder": "app",
   "lines": 10,
   "role": "metadata",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "components/analytics.tsx",
   "folder": "components",
   "lines": 7,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "components/billing-form.tsx",
   "folder": "components",
   "lines": 90,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 5
  },
  {
   "path": "components/callout.tsx",
   "folder": "components",
   "lines": 27,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 1
  },
  {
   "path": "components/card-skeleton.tsx",
   "folder": "components",
   "lines": 17,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 2
  },
  {
   "path": "components/editor.tsx",
   "folder": "components",
   "lines": 169,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 5
  },
  {
   "path": "components/empty-placeholder.tsx",
   "folder": "components",
   "lines": 79,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 2
  },
  {
   "path": "components/header.tsx",
   "folder": "components",
   "lines": 21,
   "role": null,
   "label": null,
   "fanIn": 6,
   "fanOut": 0
  },
  {
   "path": "components/icons.tsx",
   "folder": "components",
   "lines": 72,
   "role": null,
   "label": null,
   "fanIn": 21,
   "fanOut": 0
  },
  {
   "path": "components/main-nav.tsx",
   "folder": "components",
   "lines": 61,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 4
  },
  {
   "path": "components/mdx-card.tsx",
   "folder": "components",
   "lines": 38,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 1
  },
  {
   "path": "components/mdx-components.tsx",
   "folder": "components",
   "lines": 167,
   "role": null,
   "label": null,
   "fanIn": 4,
   "fanOut": 3
  },
  {
   "path": "components/mobile-nav.tsx",
   "folder": "components",
   "lines": 47,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 4
  },
  {
   "path": "components/mode-toggle.tsx",
   "folder": "components",
   "lines": 43,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 3
  },
  {
   "path": "components/nav.tsx",
   "folder": "components",
   "lines": 44,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 2
  },
  {
   "path": "components/page-header.tsx",
   "folder": "components",
   "lines": 25,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 1
  },
  {
   "path": "components/pager.tsx",
   "folder": "components",
   "lines": 64,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 4
  },
  {
   "path": "components/post-create-button.tsx",
   "folder": "components",
   "lines": 81,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 4
  },
  {
   "path": "components/post-item.tsx",
   "folder": "components",
   "lines": 42,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 3
  },
  {
   "path": "components/post-operations.tsx",
   "folder": "components",
   "lines": 114,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 4
  },
  {
   "path": "components/search.tsx",
   "folder": "components",
   "lines": 37,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 3
  },
  {
   "path": "components/shell.tsx",
   "folder": "components",
   "lines": 17,
   "role": null,
   "label": null,
   "fanIn": 6,
   "fanOut": 1
  },
  {
   "path": "components/sidebar-nav.tsx",
   "folder": "components",
   "lines": 67,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 1
  },
  {
   "path": "components/site-footer.tsx",
   "folder": "components",
   "lines": 58,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 4
  },
  {
   "path": "components/tailwind-indicator.tsx",
   "folder": "components",
   "lines": 16,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "components/theme-provider.tsx",
   "folder": "components",
   "lines": 9,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "components/toc.tsx",
   "folder": "components",
   "lines": 114,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 3
  },
  {
   "path": "components/ui/accordion.tsx",
   "folder": "components/ui",
   "lines": 60,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/alert-dialog.tsx",
   "folder": "components/ui",
   "lines": 150,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 2
  },
  {
   "path": "components/ui/alert.tsx",
   "folder": "components/ui",
   "lines": 59,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 1
  },
  {
   "path": "components/ui/aspect-ratio.tsx",
   "folder": "components/ui",
   "lines": 7,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "components/ui/avatar.tsx",
   "folder": "components/ui",
   "lines": 50,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 1
  },
  {
   "path": "components/ui/badge.tsx",
   "folder": "components/ui",
   "lines": 36,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/button.tsx",
   "folder": "components/ui",
   "lines": 51,
   "role": null,
   "label": null,
   "fanIn": 17,
   "fanOut": 1
  },
  {
   "path": "components/ui/calendar.tsx",
   "folder": "components/ui",
   "lines": 64,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 2
  },
  {
   "path": "components/ui/card.tsx",
   "folder": "components/ui",
   "lines": 79,
   "role": null,
   "label": null,
   "fanIn": 5,
   "fanOut": 1
  },
  {
   "path": "components/ui/checkbox.tsx",
   "folder": "components/ui",
   "lines": 30,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/collapsible.tsx",
   "folder": "components/ui",
   "lines": 11,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "components/ui/command.tsx",
   "folder": "components/ui",
   "lines": 155,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 2
  },
  {
   "path": "components/ui/context-menu.tsx",
   "folder": "components/ui",
   "lines": 200,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/dialog.tsx",
   "folder": "components/ui",
   "lines": 128,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 1
  },
  {
   "path": "components/ui/dropdown-menu.tsx",
   "folder": "components/ui",
   "lines": 200,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 1
  },
  {
   "path": "components/ui/hover-card.tsx",
   "folder": "components/ui",
   "lines": 29,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/input.tsx",
   "folder": "components/ui",
   "lines": 25,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 1
  },
  {
   "path": "components/ui/label.tsx",
   "folder": "components/ui",
   "lines": 26,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 1
  },
  {
   "path": "components/ui/menubar.tsx",
   "folder": "components/ui",
   "lines": 236,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/navigation-menu.tsx",
   "folder": "components/ui",
   "lines": 128,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/popover.tsx",
   "folder": "components/ui",
   "lines": 31,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/progress.tsx",
   "folder": "components/ui",
   "lines": 28,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/radio-group.tsx",
   "folder": "components/ui",
   "lines": 44,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/scroll-area.tsx",
   "folder": "components/ui",
   "lines": 48,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/select.tsx",
   "folder": "components/ui",
   "lines": 120,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/separator.tsx",
   "folder": "components/ui",
   "lines": 31,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/sheet.tsx",
   "folder": "components/ui",
   "lines": 230,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/skeleton.tsx",
   "folder": "components/ui",
   "lines": 15,
   "role": null,
   "label": null,
   "fanIn": 3,
   "fanOut": 1
  },
  {
   "path": "components/ui/slider.tsx",
   "folder": "components/ui",
   "lines": 28,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/switch.tsx",
   "folder": "components/ui",
   "lines": 29,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/tabs.tsx",
   "folder": "components/ui",
   "lines": 55,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/textarea.tsx",
   "folder": "components/ui",
   "lines": 24,
   "role": null,
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/toast.tsx",
   "folder": "components/ui",
   "lines": 127,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 1
  },
  {
   "path": "components/ui/toaster.tsx",
   "folder": "components/ui",
   "lines": 35,
   "role": null,
   "label": "component",
   "fanIn": 1,
   "fanOut": 2
  },
  {
   "path": "components/ui/toggle.tsx",
   "folder": "components/ui",
   "lines": 45,
   "role": null,
   "label": "component",
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/tooltip.tsx",
   "folder": "components/ui",
   "lines": 30,
   "role": null,
   "label": "component",
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "components/ui/use-toast.ts",
   "folder": "components/ui",
   "lines": 189,
   "role": "hook",
   "label": null,
   "fanIn": 8,
   "fanOut": 1
  },
  {
   "path": "components/user-account-nav.tsx",
   "folder": "components",
   "lines": 65,
   "role": null,
   "label": "component",
   "fanIn": 1,
   "fanOut": 2
  },
  {
   "path": "components/user-auth-form.tsx",
   "folder": "components",
   "lines": 119,
   "role": null,
   "label": "component",
   "fanIn": 2,
   "fanOut": 7
  },
  {
   "path": "components/user-avatar.tsx",
   "folder": "components",
   "lines": 24,
   "role": null,
   "label": "component",
   "fanIn": 1,
   "fanOut": 2
  },
  {
   "path": "components/user-name-form.tsx",
   "folder": "components",
   "lines": 121,
   "role": null,
   "label": "component",
   "fanIn": 1,
   "fanOut": 8
  },
  {
   "path": "config/dashboard.ts",
   "folder": "config",
   "lines": 32,
   "role": null,
   "label": "config",
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "config/docs.ts",
   "folder": "config",
   "lines": 136,
   "role": null,
   "label": "config",
   "fanIn": 3,
   "fanOut": 0
  },
  {
   "path": "config/marketing.ts",
   "folder": "config",
   "lines": 22,
   "role": null,
   "label": "config",
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "config/site.ts",
   "folder": "config",
   "lines": 13,
   "role": null,
   "label": "config",
   "fanIn": 8,
   "fanOut": 0
  },
  {
   "path": "config/subscriptions.ts",
   "folder": "config",
   "lines": 15,
   "role": null,
   "label": "config",
   "fanIn": 2,
   "fanOut": 1
  },
  {
   "path": "contentlayer.config.js",
   "folder": ".",
   "lines": 181,
   "role": "config",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "env.mjs",
   "folder": ".",
   "lines": 41,
   "role": null,
   "label": "config",
   "fanIn": 11,
   "fanOut": 0
  },
  {
   "path": "hooks/use-lock-body.ts",
   "folder": "hooks",
   "lines": 12,
   "role": "hook",
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "hooks/use-mounted.ts",
   "folder": "hooks",
   "lines": 11,
   "role": "hook",
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "lib/auth.ts",
   "folder": "lib",
   "lines": 105,
   "role": null,
   "label": "config",
   "fanIn": 11,
   "fanOut": 3
  },
  {
   "path": "lib/db.ts",
   "folder": "lib",
   "lines": 18,
   "role": null,
   "label": "repository",
   "fanIn": 8,
   "fanOut": 0
  },
  {
   "path": "lib/exceptions.ts",
   "folder": "lib",
   "lines": 5,
   "role": null,
   "label": "model",
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "lib/session.ts",
   "folder": "lib",
   "lines": 9,
   "role": null,
   "label": "service",
   "fanIn": 5,
   "fanOut": 1
  },
  {
   "path": "lib/stripe.ts",
   "folder": "lib",
   "lines": 8,
   "role": null,
   "label": "service",
   "fanIn": 3,
   "fanOut": 1
  },
  {
   "path": "lib/subscription.ts",
   "folder": "lib",
   "lines": 39,
   "role": null,
   "label": "service",
   "fanIn": 3,
   "fanOut": 2
  },
  {
   "path": "lib/toc.ts",
   "folder": "lib",
   "lines": 79,
   "role": null,
   "label": "util",
   "fanIn": 3,
   "fanOut": 0
  },
  {
   "path": "lib/utils.ts",
   "folder": "lib",
   "lines": 21,
   "role": null,
   "label": null,
   "fanIn": 66,
   "fanOut": 1
  },
  {
   "path": "lib/validations/auth.ts",
   "folder": "lib/validations",
   "lines": 5,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "lib/validations/og.ts",
   "folder": "lib/validations",
   "lines": 7,
   "role": null,
   "label": null,
   "fanIn": 1,
   "fanOut": 0
  },
  {
   "path": "lib/validations/post.ts",
   "folder": "lib/validations",
   "lines": 8,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 0
  },
  {
   "path": "lib/validations/user.ts",
   "folder": "lib/validations",
   "lines": 5,
   "role": null,
   "label": null,
   "fanIn": 2,
   "fanOut": 0
  },
  {
   "path": "middleware.ts",
   "folder": ".",
   "lines": 46,
   "role": "middleware",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "next.config.mjs",
   "folder": ".",
   "lines": 17,
   "role": "config",
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "pages/api/auth/[...nextauth].ts",
   "folder": "pages/api/auth",
   "lines": 6,
   "role": "endpoint",
   "label": null,
   "fanIn": 0,
   "fanOut": 1
  },
  {
   "path": "postcss.config.js",
   "folder": ".",
   "lines": 6,
   "role": "config",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "prettier.config.js",
   "folder": ".",
   "lines": 33,
   "role": "config",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  },
  {
   "path": "tailwind.config.js",
   "folder": ".",
   "lines": 82,
   "role": "config",
   "label": null,
   "fanIn": 0,
   "fanOut": 0
  }
 ],
 "edges": [
  {
   "from": "app/(marketing)/blog/[...slug]/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/route.ts",
   "to": "lib/subscription.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/session.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/avatar.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "components/post-item.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-account-nav.tsx",
   "to": "components/user-avatar.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mode-toggle.tsx",
   "to": "components/ui/dropdown-menu.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/login/page.tsx",
   "to": "components/user-auth-form.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-operations.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/tabs.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mdx-components.tsx",
   "to": "components/callout.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/[postId]/route.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "components/mdx-components.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/register/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/popover.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-account-nav.tsx",
   "to": "components/ui/dropdown-menu.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/page.tsx",
   "to": "components/page-header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/[...slug]/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/calendar.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/checkbox.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/webhooks/stripe/route.ts",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/[userId]/route.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/[userId]/route.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mobile-nav.tsx",
   "to": "hooks/use-lock-body.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/command.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/blog/[...slug]/page.tsx",
   "to": "components/mdx-components.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mdx-card.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/page.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/scroll-area.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/dialog.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/auth/[...nextauth]/_route.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/use-toast.ts",
   "to": "components/ui/toast.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/search.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "config/docs.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "config/subscriptions.ts",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "components/ui/label.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/main-nav.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "components/pager.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/card.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/ui/label.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "lib/session.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/[...slug]/page.tsx",
   "to": "components/mdx-components.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mdx-components.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/slider.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/alert-dialog.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-operations.tsx",
   "to": "components/ui/dropdown-menu.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/stripe/route.ts",
   "to": "lib/subscription.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-item.tsx",
   "to": "components/ui/skeleton.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "components/page-header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/loading.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/editor.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/[postId]/route.ts",
   "to": "lib/validations/post.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/page.tsx",
   "to": "lib/session.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/billing-form.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/register/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/toc.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/calendar.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "lib/session.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/[...slug]/page.tsx",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/[userId]/route.ts",
   "to": "lib/validations/user.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "components/search.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/toc.tsx",
   "to": "lib/toc.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/sheet.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/toaster.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/auth.ts",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-create-button.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/radio-group.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/register/page.tsx",
   "to": "components/user-auth-form.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/page.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mode-toggle.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/toggle.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "components/toc.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "lib/subscription.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/subscription.ts",
   "to": "config/subscriptions.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-item.tsx",
   "to": "components/post-operations.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-avatar.tsx",
   "to": "components/ui/avatar.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/page.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/stripe/route.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/alert.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/pricing/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-create-button.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-item.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/layout.tsx",
   "to": "components/sidebar-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/site-footer.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/loading.tsx",
   "to": "components/card-skeleton.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/empty-placeholder.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "components/theme-provider.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/sidebar-nav.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "lib/stripe.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-operations.tsx",
   "to": "components/ui/alert-dialog.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/webhooks/stripe/route.ts",
   "to": "lib/stripe.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/input.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "components/tailwind-indicator.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/blog/[...slug]/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "lib/validations/user.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/stripe/route.ts",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "components/post-create-button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/command.tsx",
   "to": "components/ui/dialog.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/billing-form.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/[...slug]/page.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/layout.tsx",
   "to": "components/site-footer.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "components/main-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/pager.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-avatar.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/login/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/billing-form.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/loading.tsx",
   "to": "components/post-item.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "components/analytics.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/accordion.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/page-header.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/main-nav.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/badge.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/not-found.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/loading.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/blog/[...slug]/page.tsx",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/route.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/menubar.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-operations.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/site-footer.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "components/main-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/billing-form.tsx",
   "to": "components/ui/card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/layout.tsx",
   "to": "components/main-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/billing-form.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/search.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/site-footer.tsx",
   "to": "components/mode-toggle.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/ui/card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/pager.tsx",
   "to": "config/docs.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "components/nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/stripe/route.ts",
   "to": "config/subscriptions.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/auth.ts",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/route.ts",
   "to": "lib/exceptions.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/switch.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/search.tsx",
   "to": "components/ui/input.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/navigation-menu.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/loading.tsx",
   "to": "components/card-skeleton.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/skeleton.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "lib/session.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/loading.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/page.tsx",
   "to": "components/user-name-form.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/loading.tsx",
   "to": "components/ui/skeleton.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/select.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/toast.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/card-skeleton.tsx",
   "to": "components/ui/skeleton.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "components/user-account-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/page.tsx",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/site-footer.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/tooltip.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/pricing/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/main-nav.tsx",
   "to": "components/mobile-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/billing-form.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/og/route.tsx",
   "to": "lib/validations/og.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "pages/api/auth/[...nextauth].ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "components/site-footer.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "components/sidebar-nav.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/editor.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/[[...slug]]/page.tsx",
   "to": "lib/toc.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/shell.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/loading.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/utils.ts",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/page.tsx",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/empty-placeholder.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "components/mdx-components.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/login/page.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "lib/toc.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/editor.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/webhooks/stripe/route.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/separator.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/main-nav.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/users/stripe/route.ts",
   "to": "lib/stripe.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/layout.tsx",
   "to": "config/dashboard.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/loading.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/loading.tsx",
   "to": "components/post-create-button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mobile-nav.tsx",
   "to": "config/site.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/pager.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/ui/card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/route.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/ui/alert.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/editor.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/layout.tsx",
   "to": "components/site-footer.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/page.tsx",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mobile-nav.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mode-toggle.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/api/posts/[postId]/route.ts",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/nav.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-create-button.tsx",
   "to": "components/ui/use-toast.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/loading.tsx",
   "to": "components/ui/card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/toaster.tsx",
   "to": "components/ui/toast.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/nav.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mobile-nav.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "components/toc.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "components/ui/input.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/blog/page.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/hover-card.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/textarea.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/editor.tsx",
   "to": "lib/validations/post.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/layout.tsx",
   "to": "components/ui/toaster.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/button.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/context-menu.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/login/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/page.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/mdx-components.tsx",
   "to": "components/mdx-card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/label.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/alert-dialog.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/pricing/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/docs/layout.tsx",
   "to": "config/docs.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/dropdown-menu.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/layout.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "components/shell.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "components/page-header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/settings/page.tsx",
   "to": "lib/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/blog/[...slug]/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-name-form.tsx",
   "to": "components/ui/input.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "lib/validations/auth.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/callout.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/page.tsx",
   "to": "components/editor.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/stripe.ts",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "next.config.mjs",
   "to": "env.mjs",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/user-auth-form.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/billing/loading.tsx",
   "to": "components/header.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/layout.tsx",
   "to": "components/ui/button.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/subscription.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/ui/progress.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(docs)/guides/[...slug]/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/not-found.tsx",
   "to": "components/empty-placeholder.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(marketing)/layout.tsx",
   "to": "config/marketing.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(editor)/editor/[postId]/page.tsx",
   "to": "lib/session.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "lib/auth.ts",
   "to": "lib/db.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/post-create-button.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/card-skeleton.tsx",
   "to": "components/ui/card.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(auth)/register/page.tsx",
   "to": "components/icons.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "app/(dashboard)/dashboard/page.tsx",
   "to": "components/empty-placeholder.tsx",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/toc.tsx",
   "to": "hooks/use-mounted.ts",
   "kinds": [
    "import"
   ]
  },
  {
   "from": "components/pager.tsx",
   "to": "lib/utils.ts",
   "kinds": [
    "import"
   ]
  }
 ],
 "routes": [
  {
   "method": "GET",
   "path": "/dashboard",
   "file": "app/(dashboard)/dashboard/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/guides/[...slug]",
   "file": "app/(docs)/guides/[...slug]/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/api/users/stripe",
   "file": "app/api/users/stripe/route.ts",
   "line": 12
  },
  {
   "method": "GET",
   "path": "/login",
   "file": "app/(auth)/login/page.tsx",
   "line": 1
  },
  {
   "method": "POST",
   "path": "/api/posts",
   "file": "app/api/posts/route.ts",
   "line": 41
  },
  {
   "method": "PATCH",
   "path": "/api/posts/[postId]",
   "file": "app/api/posts/[postId]/route.ts",
   "line": 44
  },
  {
   "method": "DELETE",
   "path": "/api/posts/[postId]",
   "file": "app/api/posts/[postId]/route.ts",
   "line": 14
  },
  {
   "method": "GET",
   "path": "/",
   "file": "app/(marketing)/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/dashboard/billing",
   "file": "app/(dashboard)/dashboard/billing/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/pricing",
   "file": "app/(marketing)/pricing/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/editor/[postId]",
   "file": "app/(editor)/editor/[postId]/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/dashboard/settings",
   "file": "app/(dashboard)/dashboard/settings/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/[...slug]",
   "file": "app/(marketing)/[...slug]/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/docs/[[...slug]]",
   "file": "app/(docs)/docs/[[...slug]]/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/api/og",
   "file": "app/api/og/route.tsx",
   "line": 15
  },
  {
   "method": "GET",
   "path": "/register",
   "file": "app/(auth)/register/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/blog/[...slug]",
   "file": "app/(marketing)/blog/[...slug]/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/blog",
   "file": "app/(marketing)/blog/page.tsx",
   "line": 1
  },
  {
   "method": "GET",
   "path": "/guides",
   "file": "app/(docs)/guides/page.tsx",
   "line": 1
  },
  {
   "method": "POST",
   "path": "/api/webhooks/stripe",
   "file": "app/api/webhooks/stripe/route.ts",
   "line": 8
  },
  {
   "method": "GET",
   "path": "/api/posts",
   "file": "app/api/posts/route.ts",
   "line": 14
  },
  {
   "method": "PATCH",
   "path": "/api/users/[userId]",
   "file": "app/api/users/[userId]/route.ts",
   "line": 14
  }
 ],
 "withheldRoutes": [
  {
   "file": "app/robots.ts",
   "line": 1,
   "reason": "Next generates this file's URL, with an extension and sometimes an id"
  },
  {
   "file": "pages/api/auth/[...nextauth].ts",
   "line": 1,
   "reason": "One default export answers every method; which ones it handles is decided at runtime"
  }
 ]
};
