// Freezes one stored analysis into the public demo.
//
//   pnpm demo:export <analysis id>
//
// The demo is read from a file in the repository, never from the database, so
// a visitor who arrives while the free Supabase project is paused still sees a
// map. It is a real analysis exported as stored, not a drawing of one. Run the
// pipeline on the repository first (`pnpm analyze`), then this.

import "./load-env.ts";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { readStoredMap } from "../lib/analyses/map.ts";
import { createAdminClient } from "../lib/supabase/admin.ts";

const id = process.argv[2];
if (id === undefined) {
  console.error("usage: pnpm demo:export <analysis id>");
  process.exit(1);
}

const map = await readStoredMap(createAdminClient(), id);
if (map === null) {
  console.error(`analysis ${id} doesn't exist or has nothing stored`);
  process.exit(1);
}
if (map.status !== "complete" || map.finishedAt === null) {
  console.error(`analysis ${id} is ${map.status}; export a finished one`);
  process.exit(1);
}

const out = path.resolve(import.meta.dirname, "../lib/demo/snapshot.ts");
const source = `// Generated by scripts/export-demo.ts from a stored analysis. Don't edit by
// hand: run the pipeline again and re-export.

import type { StoredMap } from "../analyses/map.ts";

export const demo: StoredMap = ${JSON.stringify(map, null, 1)};
`;
writeFileSync(out, source);
console.log(
  `${map.repoOwner}/${map.repoName} at ${map.commitSha.slice(0, 7)}: ${map.files.length} files, ${map.edges.length} edges, ${map.routes.length} routes → ${path.relative(process.cwd(), out)}`,
);
